### ISSUE TITLE
Detection score greater than 0.9 for wrong detections

### ISSUE THREAD

**Issue by vkramdev** [TannerGilbert/MaskRCNN-Object-Detection-and-Segmentation#2]
Hi Gilbert,

I am using matterport implementation of maskrcnn. I have trained my model on my custom dataset , however during inference if the instance is not detected correctly in an image ,say a ball is detected as knife even in this case the score shown with ball is 0.978 . 

How do i reduce this score so that it conveys better message say the instance is detected as knife however the score is something like 0.5 or 0.4. 

What should i be looking into to resolve this . Any help or suggestion is appreciated.

Thanks in advance.

**Comment by TannerGilbert** [comment]
Maybe getting more training images or using data augmentation could help
